Add health check in CI/CD pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -46,4 +46,17 @@ jobs:
             echo "Running compose."
             docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
 
-            echo "Finished."
+            echo "Checking app health."
+            for i in {1..10}; do
+              if curl -fs http://localhost:8101/health > /dev/null; then
+                echo "App is healthy!"
+                echo "Finished."
+                exit 0
+              else
+                echo "Not healthy yet... retrying ($i/5)"
+                sleep 5
+              fi
+            done
+
+            echo "ERROR: app did not become healthy."
+            exit 1
